print("Tell me your favorite movie:")
favMovie = input()
print("Tell me your favorite song:")
favSong = input()
print("What is your favorite food:")
favFood = input()
print("the " + favMovie + " is a great film!") 
print("I love to eat " + favFood + "!")
print("Never heard of " + favSong + " though.")